/**
 * @packageDocumentation
 * @module api.functional.verification.phones
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../../utils/NestiaSimulator";
import type { IVerification } from "./../../../structures/IVerification";

export * as verify from "./verify";

/**
 * 휴대전화 인증 정보를 생성한다.
 * 
 * 해당 API를 호출시, 전달된 휴대폰 번호로 문자를 전송합니다.
 * 
 * @summary 휴대전화 인증 정보 생성
 * 
 * @tag verification
 * 
 * @param body 인증받을 휴대전화 번호
 * 
 * @return 인증 만료일자(생성일로부터 5분)
 * 
 * @controller VerificationPhonesController.create()
 * @path POST /verification/phones
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
    connection: IConnection,
    body: IVerification.IRequest.ICreatePhone,
): Promise<create.Output> {
    return !!connection.simulate
        ? create.simulate(
              connection,
              body,
          )
        : Fetcher.fetch(
              connection,
              create.ENCRYPTED,
              create.METHOD,
              create.path(),
              body,
              create.stringify,
          );
}
export namespace create {
    export type Input = IVerification.IRequest.ICreatePhone;
    export type Output = IVerification.IResponse.ICreate;

    export const METHOD = "POST" as const;
    export const PATH: string = "/verification/phones";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/verification/phones`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        body: create.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path()
        });
        assert.body(() => typia.assert(body));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}