/**
 * @packageDocumentation
 * @module api.functional.users.biz_users.hs_providers.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { IHSProvider } from "./../../../../../structures/user/IHSProvider";

export * as portfolios from "./portfolios";
export * as biz_info from "./biz_info";
export * as expertise from "./expertise";

/**
 * 생활서비스 전문가 개인정보를 요청한다.
 * 
 * 이메일, 휴대전화 등의 개인 정보는 마킹처리되어 전달된다.
 * 
 * {@link IHSProvider.FailureCode.GetPrivate 에러 코드}
 * 
 * @summary 생활서비스 전문가 내 정보 조회
 * @tag hs-providers
 * @security access
 * @return 생활서비스 전문가 상세 정보
 * 
 * @controller UsersHSProvidersMeController.get()
 * @path GET /users/biz-users/hs-providers/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
    connection: IConnection,
): Promise<get.Output> {
    return !!connection.simulate
        ? get.simulate(
              connection,
          )
        : Fetcher.fetch(
              connection,
              get.ENCRYPTED,
              get.METHOD,
              get.path(),
          );
}
export namespace get {
    export type Output = IHSProvider;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/biz-users/hs-providers/me";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/users/biz-users/hs-providers/me`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
    ): Promise<Output> => {
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}