/**
 * @packageDocumentation
 * @module api.functional.auth.token
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as access from "./access";