/**
 * @packageDocumentation
 * @module api.functional.users.biz_users.hs_providers.me.expertise
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../../../../../utils/NestiaSimulator";
import type { IHSProvider } from "./../../../../../../structures/user/IHSProvider";

/**
 * 생활서비스 전문가 전문분야 수정
 * 
 * @summary 생활서비스 전문가 전문분야 수정
 * 
 * @tag hs-providers
 * 
 * @param access_token Authorization access access_token
 * 
 * @param body 프로필 이미지 정보
 * 
 * @controller UsersHSProvidersExpertiseUpdateController.update()
 * @path PUT /users/biz-users/hs-providers/me/expertise
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
    connection: IConnection,
    body: IHSProvider.IUpdate.ISubExpertise,
): Promise<void> {
    return !!connection.simulate
        ? update.simulate(
              connection,
              body,
          )
        : Fetcher.fetch(
              connection,
              update.ENCRYPTED,
              update.METHOD,
              update.path(),
              body,
              update.stringify,
          );
}
export namespace update {
    export type Input = IHSProvider.IUpdate.ISubExpertise;

    export const METHOD = "PUT" as const;
    export const PATH: string = "/users/biz-users/hs-providers/me/expertise";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/users/biz-users/hs-providers/me/expertise`;
    }
    export const simulate = async (
        connection: IConnection,
        body: update.Input,
    ): Promise<void> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path()
        });
        assert.body(() => typia.assert(body));
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}