/**
 * @packageDocumentation
 * @module api.functional.verification
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as phones from "./phones";