/**
 * @packageDocumentation
 * @module api.functional.users.biz_users.hs_providers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../../../utils/NestiaSimulator";
import type { IHSProvider } from "./../../../../structures/user/IHSProvider";

export * as me from "./me";
export * as contact from "./contact";
export * as portfolios from "./portfolios";

/**
 * 검색기준에 맞는 인증된 생활서비스 전문가 간단 정보 목록을 확안할 수 있다.
 * 
 * @summary 생활서비스 전문가 목록 검색
 * 
 * @tag hs-providers
 * 
 * @param query 필터링, 정렬 기준
 * 
 * @return 생활서비스 전문가 간단 정보 목록
 * 
 * @controller UsersHSProvidersController.getList()
 * @path GET /users/biz-users/hs-providers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getList(
    connection: IConnection,
    query: IHSProvider.ISearch,
): Promise<getList.Output> {
    return !!connection.simulate
        ? getList.simulate(
              connection,
              query,
          )
        : Fetcher.fetch(
              connection,
              getList.ENCRYPTED,
              getList.METHOD,
              getList.path(query),
          );
}
export namespace getList {
    export type Query = IHSProvider.ISearch;
    export type Output = IHSProvider.IPaginatedSummary;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/biz-users/hs-providers";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (query: getList.Query): string => {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/users/biz-users/hs-providers${encoded.length ? `?${encoded}` : ""}`;;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        query: getList.Query,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path(query)
        });
        assert.query(() => typia.assert(query));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * 생활서비스 전문가의 공개 정보를 요청한다.
 * 
 * {@link IHSProvider.FailureCode.GetPublic 에러 코드}
 * 
 * @summary 생활서비스 전문가 공개 프로필 정보 조회
 * 
 * @tag hs-providers
 * 
 * @param provider_id 생활서비스 전문가 id
 * 
 * @return 생활서비스 전문가 공개정보
 * 
 * @controller UsersHSProvidersSomeoneController.getOne()
 * @path GET /users/biz-users/hs-providers/:provider_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOne(
    connection: IConnection,
    provider_id: string,
): Promise<getOne.Output> {
    return !!connection.simulate
        ? getOne.simulate(
              connection,
              provider_id,
          )
        : Fetcher.fetch(
              connection,
              getOne.ENCRYPTED,
              getOne.METHOD,
              getOne.path(provider_id),
          );
}
export namespace getOne {
    export type Output = IHSProvider.IPublic;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/biz-users/hs-providers/:provider_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (provider_id: string): string => {
        return `/users/biz-users/hs-providers/${encodeURIComponent(provider_id ?? "null")}`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        provider_id: string,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path(provider_id)
        });
        assert.param("provider_id")("string")(() => typia.assert(provider_id));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}