/**
 * @packageDocumentation
 * @module api.functional.users.biz_users.hs_providers.portfolios
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../../../../utils/NestiaSimulator";
import type { IHSPortfolio } from "./../../../../../structures/IHSPortfolio";

/**
 * 생활서비스 전문가 포트폴리오 목록 검색
 * 
 * {@link IHSProvider.FailureCode.GetPublic 에러 코드}
 * 
 * @summary 생활서비스 전문가 포트폴리오 목록 검색
 * 
 * @tag hs-providers
 * 
 * @param provider_id 생활서비스 전문가 id
 * 
 * @param query 페이지 정보
 * 
 * @return 포트폴리오 공개 정보 목록
 * 
 * @controller UsersHSProvidersSomeoneController.getList()
 * @path GET /users/biz-users/hs-providers/:provider_id/portfolios
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getList(
    connection: IConnection,
    provider_id: string,
    query: IHSPortfolio.ISearch,
): Promise<getList.Output> {
    return !!connection.simulate
        ? getList.simulate(
              connection,
              provider_id,
              query,
          )
        : Fetcher.fetch(
              connection,
              getList.ENCRYPTED,
              getList.METHOD,
              getList.path(provider_id, query),
          );
}
export namespace getList {
    export type Query = IHSPortfolio.ISearch;
    export type Output = IHSPortfolio.IPaginatedPublic;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/biz-users/hs-providers/:provider_id/portfolios";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (provider_id: string, query: getList.Query): string => {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/users/biz-users/hs-providers/${encodeURIComponent(provider_id ?? "null")}/portfolios${encoded.length ? `?${encoded}` : ""}`;;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        provider_id: string,
        query: getList.Query,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path(provider_id, query)
        });
        assert.param("provider_id")("string")(() => typia.assert(provider_id));
        assert.query(() => typia.assert(query));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}