# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

name: Docker Image Push 🔖

on:
    push:
        tags: v*

env:
    ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
    id-token: write
    contents: read

jobs:
    build_and_push:
        name: Docker Image Build & Push
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@main

            - name: Configure AWS credentials 🔒
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR 🔒
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Read package.json version 🔖
              id: read-version
              run: |
                  echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

            - name: Image Build and Push to Amazon ECR ✨
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  IMAGE_TAG: ${{ steps.read-version.outputs.VERSION }}
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
